<a href="https://colab.research.google.com/github/sabafsadeghi-coder/NumPy-task/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
  # Saba fatima sadeghi
# AI-873629

In [ ]:
# Task 1:
import numpy as np

marks = np.array([10, 20, 30, 40, 50])

print(np.sum(marks))

print(np.mean(marks))

print(np.max(marks))

print(np.min(marks))

150
30.0
50
10


In [ ]:
# Task 2:
import numpy as np

numbers = np.array([45, 80, 30, 90, 55, 20])

result = numbers[numbers >= 50]

print(result)


[80 90 55]


In [ ]:
# Task 3:
import numpy as np

data = np.array([
    [1, 2, 3],
    [4, 5, 6]

])
print(data.shape)


(2, 3)


In [ ]:
# Task 4:
import numpy as np

marks = np.random.randint(40, 101, 10)

print("Marks:", marks)
print("Average:", np.mean(marks))
print("Highest marks:", np.max(marks))
print("Lowest:", np.min(marks))


Marks: [64 81 84 83 90 70 68 89 89 69]
Average: 78.7
Highest marks: 90
Lowest: 64


In [ ]:
# Task 5:
import numpy as np

marks = np.array([60, 40, 30, 50, 20, 80])

passed = marks[marks >= 50]
fail = marks[marks < 50]

print("Passed:", passed)
print(len(passed))
print("Fail:", fail)
print(len(fail))


Passed: [60 50 80]
3
Fail: [40 30 20]
3


In [ ]:
# 1- Import NumPy:

import numpy as np

numbers = np.array([20, 40, 60, 80, 100])

print(numbers)


[10 20 30 40 50]


In [ ]:
# 2- Python list vs NumPy Array :

import numpy as np

# Python List
my_list = [20, 40, 60, 80, 100]

# NumPy Array
my_array = np.array([20, 40, 60, 80, 100])

print("Python List:", my_list)
print("NumPy Array:", my_array)

Python List: [10, 20, 30, 40, 50]
NumPy Array: [10 20 30 40 50]


In [ ]:
# 3- Creating NumPy Arrays :

import numpy as np

# Creating an array from a list
numbers = np.array([20, 40, 60, 80, 100])

# Creating a 2D array
matrix = np.array([[2, 4, 6],
                   [8, 10, 12]])

print("1D Array:", numbers)
print("2D Array:")


1D Array: [ 20  40  60  80 100]
2D Array:


In [ ]:
# 4- Important Array Properties :

import numpy as np

data = np.array([[2, 4, 6],
                 [20, 40, 60]])

print("Shape:", data.shape)
print("Size:", data.size)
print("Number of dimensions:", data.ndim)
print("Data type:", data.dtype)

Shape: (2, 3)
Size: 6
Number of dimensions: 2
Data type: int64


In [ ]:
# 5- Indexing :

import numpy as np

numbers = np.array([10, 20, 30, 40, 50])

print(numbers[-2])
print(numbers[0])
print(numbers[2])

40
10
30


In [ ]:
# 6-Indexing in a 2D Arrays:

import numpy as np

data = np.array([[2, 4, 6],
                 [20, 40, 60]])

print(data[0, 0])
print(data[0, 2])
print(data[1, 1])

2
6
40


In [ ]:
# 7- Slicing :

import numpy as np

numbers = np.array([20, 40, 60, 80, 100])

print(numbers[1:4])

[40 60 80]


In [ ]:
# 8- Vectorized Operations :

import numpy as np

numbers = np.array([20, 40, 60, 80, 100])

print(numbers + 5)
print(numbers * 2)
print(numbers - 5)
print(numbers / 2)

[ 25  45  65  85 105]
[ 40  80 120 160 200]
[15 35 55 75 95]
[10. 20. 30. 40. 50.]


In [ ]:
# 9- Operations Between Two Array :

import numpy as np

a = np.array([20, 40, 60])
b = np.array([2, 4, 6])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)



Addition: [22 44 66]
Subtraction: [18 36 54]
Multiplication: [ 40 160 360]
Division: [10. 10. 10.]


In [ ]:
# 10- Mathematical Functions :

import numpy as np

numbers = np.array([9, 16, 49, 81])

print("Square root:", np.sqrt(numbers))
print("Absolute value:", np.abs(numbers))
print("Sum:", np.sum(numbers))
print("Maximum:", np.max(numbers))
print("Minimum:", np.min(numbers))

Square root: [3. 4. 7. 9.]
Absolute value: [ 9 16 49 81]
Sum: 155
Maximum: 81
Minimum: 9


In [ ]:
# 11- Aggregation Functions :

import numpy as np

marks = np.array([20, 40, 60, 80, 100])

print("Sum:", np.sum(marks))
print("Mean:", np.mean(marks))
print("Maximum:", np.max(marks))
print("Minimum:", np.min(marks))
print("Median:", np.median(marks))
print("Standard Deviation:", np.std(marks))


Sum: 300
Mean: 60.0
Maximum: 100
Minimum: 20
Median: 60.0
Standard Deviation: 28.284271247461902


In [ ]:
# 12- Conditions in NumPy :

import numpy as np

marks = np.array([20, 40, 60, 80, 100])

result = marks >= 50

print(result)

[False False  True  True  True]


In [ ]:
# 13- Filtering Data :

import numpy as np

marks = np.array([20, 40, 60, 80, 100, 110, 120])

filtered_marks = marks[marks >= 50]

print("Filtered marks:", filtered_marks)

Filtered marks: [ 60  80 100 110 120]


In [ ]:
# 14- Reshape :

import numpy as np

numbers = np.array([2, 4, 6, 8, 10, 12])

new_array = numbers.reshape(2, 3)

print(new_array)

[[ 2  4  6]
 [ 8 10 12]]


In [ ]:
# 15- Flatten :

import numpy as np

data = np.array([[2, 4, 6],
                 [8, 10, 12]])

flat_data = data.flatten()

print("Original array:")
print(data)

print("Flattened array:")
print(flat_data)

Original array:
[[ 2  4  6]
 [ 8 10 12]]
Flattened array:
[ 2  4  6  8 10 12]


In [ ]:
# 16- Useful NumPy Functions :

import numpy as np

numbers = np.array([20, 40, 60, 80, 100])

print("Sum:", np.sum(numbers))
print("Mean:", np.mean(numbers))
print("Maximum:", np.max(numbers))
print("Minimum:", np.min(numbers))
print("Standard Deviation:", np.std(numbers))
print("Square Root:", np.sqrt(numbers))

Sum: 300
Mean: 60.0
Maximum: 100
Minimum: 20
Standard Deviation: 28.284271247461902
Square Root: [ 4.47213595  6.32455532  7.74596669  8.94427191 10.        ]


In [ ]:
# 17- Random Numbers :

import numpy as np

numbers = np.random.randint(1, 101, 5)

print(numbers)

[10 35 62 91 39]
